spring.application.name=ms_reportes


# Webhook target for monitor service

ms.monitor.url=http://localhost:8082

ms.alertas.url=http://172.28.0.13:8083


# JWT secret used to sign service-to-service tokens (must match ms_monitoreo.jwt.secret)

jwt.secret=changeitchangethischangethisisverysecretkeyforjwthmacsha256algorithm


# File upload

file.upload-dir=uploads

# 50 MB

file.max-size-bytes=52428800 



spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
